name: podsbyme
description: A podcast listener app.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  podcast_search: ^0.6.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
